# Generated by Powerlevel10k configuration wizard
# Based on: Rainbow style, Unicode, Round separators/heads, Blurred tails
# One line, Sparse spacing, Many icons, Concise flow, Transient prompt

# Temporarily change options
'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh -o extended_glob

  # Unset all configuration options
  unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'

  # Zsh >= 5.1 is required
  [[ $ZSH_VERSION == (5.<1->*|<6->.*) ]] || return

  # Prompt mode: nerdfont-complete for full icon support
  typeset -g POWERLEVEL9K_MODE=nerdfont-complete

  # Icon padding
  typeset -g POWERLEVEL9K_ICON_PADDING=none

  # Background color for prompt
  typeset -g POWERLEVEL9K_BACKGROUND=

  # Left prompt elements
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    os_icon                 # os identifier
    dir                     # current directory
    vcs                     # git status
  )

  # Right prompt elements
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    status                  # exit code of the last command
    command_execution_time  # duration of the last command
    background_jobs         # presence of background jobs
    direnv                  # direnv status
    asdf                    # asdf version manager
    virtualenv              # python virtual environment
    anaconda                # conda environment
    pyenv                   # python version from pyenv
    goenv                   # go version from goenv
    nodenv                  # node.js version from nodenv
    nvm                     # node.js version from nvm
    nodeenv                 # node.js environment
    node_version            # node.js version
    go_version              # go version
    rust_version            # rust version
    dotnet_version          # .NET version
    php_version             # php version
    laravel_version         # laravel version
    java_version            # java version
    package                 # name@version from package.json
    rbenv                   # ruby version from rbenv
    rvm                     # ruby version from rvm
    fvm                     # flutter version from fvm
    luaenv                  # lua version from luaenv
    jenv                    # java version from jenv
    plenv                   # perl version from plenv
    perlbrew                # perl version from perlbrew
    phpenv                  # php version from phpenv
    scalaenv                # scala version from scalaenv
    haskell_stack           # haskell version from stack
    kubecontext             # kubernetes context
    terraform               # terraform workspace
    terraform_version       # terraform version
    aws                     # aws profile
    aws_eb_env              # aws elastic beanstalk
    azure                   # azure account
    gcloud                  # google cloud account
    google_app_cred         # google application credentials
    toolbox                 # toolbox name
    context                 # user@hostname
    nordvpn                 # nordvpn connection status
    ranger                  # ranger shell
    nnn                     # nnn shell
    lf                      # lf shell
    xplr                    # xplr shell
    vim_shell               # vim shell indicator
    midnight_commander      # midnight commander shell
    nix_shell               # nix shell
    chezmoi_shell           # chezmoi shell
    vi_mode                 # vi mode
    time                    # current time
  )

  # Basic style options
  typeset -g POWERLEVEL9K_VISUAL_IDENTIFIER_EXPANSION='${P9K_VISUAL_IDENTIFIER}'

  # Separators - Round style
  typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='\uE0B1'
  typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='\uE0B3'
  typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\uE0B0'
  typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\uE0B2'
  typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL='\uE0B0'
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='\uE0B2'
  typeset -g POWERLEVEL9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=''
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL=''

  # Blurred tails
  typeset -g POWERLEVEL9K_EMPTY_LINE_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=

  # Prompt on one line
  typeset -g POWERLEVEL9K_PROMPT_ON_NEWLINE=false

  # Sparse spacing - add empty line before prompt
  typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

  # Transient prompt
  typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=always

  # Instant prompt mode
  typeset -g POWERLEVEL9K_INSTANT_PROMPT=verbose

  # Hot reload
  typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=true

  ##################################[ os_icon: os identifier ]##################################
  typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=255
  typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND=236

  ##################################[ dir: current directory ]##################################
  typeset -g POWERLEVEL9K_DIR_BACKGROUND=4
  typeset -g POWERLEVEL9K_DIR_FOREGROUND=254
  typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
  typeset -g POWERLEVEL9K_SHORTEN_DELIMITER=
  typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=250
  typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=255
  typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=true
  typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=80

  # Directory icons
  typeset -g POWERLEVEL9K_DIR_SHOW_WRITABLE=v3

  # Special directories
  typeset -g POWERLEVEL9K_DIR_CLASSES=(
    '~/work(|/*)'  WORK     ''
    '~(|/*)'       HOME     ''
    '*'            DEFAULT  ''
  )

  typeset -g POWERLEVEL9K_DIR_HOME_BACKGROUND=4
  typeset -g POWERLEVEL9K_DIR_HOME_FOREGROUND=254
  typeset -g POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND=4
  typeset -g POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND=254
  typeset -g POWERLEVEL9K_DIR_DEFAULT_BACKGROUND=4
  typeset -g POWERLEVEL9K_DIR_DEFAULT_FOREGROUND=254
  typeset -g POWERLEVEL9K_DIR_ETC_BACKGROUND=4
  typeset -g POWERLEVEL9K_DIR_ETC_FOREGROUND=254
  typeset -g POWERLEVEL9K_DIR_NOT_WRITABLE_BACKGROUND=1
  typeset -g POWERLEVEL9K_DIR_NOT_WRITABLE_FOREGROUND=254

  #####################################[ vcs: git status ]######################################
  typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND=2
  typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=0
  typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=3
  typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=0
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=2
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=0
  typeset -g POWERLEVEL9K_VCS_CONFLICTED_BACKGROUND=1
  typeset -g POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND=255
  typeset -g POWERLEVEL9K_VCS_LOADING_BACKGROUND=8
  typeset -g POWERLEVEL9K_VCS_LOADING_FOREGROUND=0

  # Branch icon
  typeset -g POWERLEVEL9K_VCS_BRANCH_ICON='\uF126 '

  # Untracked files icon
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON='?'

  # Git status formatting
  typeset -g POWERLEVEL9K_VCS_MAX_INDEX_SIZE_DIRTY=-1
  typeset -g POWERLEVEL9K_VCS_DISABLED_WORKDIR_PATTERN='~'

  # Git icons
  typeset -g POWERLEVEL9K_VCS_GIT_ICON=''
  typeset -g POWERLEVEL9K_VCS_GIT_GITHUB_ICON=''
  typeset -g POWERLEVEL9K_VCS_GIT_BITBUCKET_ICON=''
  typeset -g POWERLEVEL9K_VCS_GIT_GITLAB_ICON=''

  ##########################[ status: exit code of the last command ]###########################
  typeset -g POWERLEVEL9K_STATUS_EXTENDED_STATES=true

  # Status on success
  typeset -g POWERLEVEL9K_STATUS_OK=true
  typeset -g POWERLEVEL9K_STATUS_OK_BACKGROUND=0
  typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=2
  typeset -g POWERLEVEL9K_STATUS_OK_VISUAL_IDENTIFIER_EXPANSION='✔'

  # Status on error
  typeset -g POWERLEVEL9K_STATUS_ERROR=true
  typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND=1
  typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=255
  typeset -g POWERLEVEL9K_STATUS_ERROR_VISUAL_IDENTIFIER_EXPANSION='✘'

  # Status when interrupted
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL=true
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_BACKGROUND=1
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND=255

  # Status when pipe failed
  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE=true
  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_BACKGROUND=1
  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND=255

  ###################[ command_execution_time: duration of the last command ]###################
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=0
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=3
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=0
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT='d h m s'
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_VISUAL_IDENTIFIER_EXPANSION=

  #######################[ background_jobs: presence of background jobs ]#######################
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=false
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND=0
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=6
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VISUAL_IDENTIFIER_EXPANSION='⇣'

  #####################################[ context: user@host ]####################################
  typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=1
  typeset -g POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND=0
  typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_FOREGROUND=3
  typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_BACKGROUND=0
  typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND=3
  typeset -g POWERLEVEL9K_CONTEXT_BACKGROUND=0
  typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE='%n@%m'
  typeset -g POWERLEVEL9K_CONTEXT_{DEFAULT,SUDO}_{CONTENT,VISUAL_IDENTIFIER}_EXPANSION=

  ###################################[ virtualenv: python venv ]################################
  typeset -g POWERLEVEL9K_VIRTUALENV_BACKGROUND=4
  typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND=0
  typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION=false
  typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_WITH_PYENV=false
  typeset -g POWERLEVEL9K_VIRTUALENV_{LEFT,RIGHT}_DELIMITER=

  ###################################[ anaconda: conda environment ]############################
  typeset -g POWERLEVEL9K_ANACONDA_BACKGROUND=4
  typeset -g POWERLEVEL9K_ANACONDA_FOREGROUND=0
  typeset -g POWERLEVEL9K_ANACONDA_SHOW_PYTHON_VERSION=false
  typeset -g POWERLEVEL9K_ANACONDA_{LEFT,RIGHT}_DELIMITER=

  ####################################[ pyenv: python version ]#################################
  typeset -g POWERLEVEL9K_PYENV_BACKGROUND=4
  typeset -g POWERLEVEL9K_PYENV_FOREGROUND=0
  typeset -g POWERLEVEL9K_PYENV_SOURCES=(shell local global)
  typeset -g POWERLEVEL9K_PYENV_PROMPT_ALWAYS_SHOW=false
  typeset -g POWERLEVEL9K_PYENV_SHOW_SYSTEM=true

  ##################################[ node_version: node.js version ]###########################
  typeset -g POWERLEVEL9K_NODE_VERSION_BACKGROUND=2
  typeset -g POWERLEVEL9K_NODE_VERSION_FOREGROUND=0
  typeset -g POWERLEVEL9K_NODE_VERSION_PROJECT_ONLY=true

  ##################################[ go_version: go version ]##################################
  typeset -g POWERLEVEL9K_GO_VERSION_BACKGROUND=6
  typeset -g POWERLEVEL9K_GO_VERSION_FOREGROUND=0
  typeset -g POWERLEVEL9K_GO_VERSION_PROJECT_ONLY=true

  #################################[ rust_version: rust version ]###############################
  typeset -g POWERLEVEL9K_RUST_VERSION_BACKGROUND=208
  typeset -g POWERLEVEL9K_RUST_VERSION_FOREGROUND=0
  typeset -g POWERLEVEL9K_RUST_VERSION_PROJECT_ONLY=true

  ##################################[ java_version: java version ]##############################
  typeset -g POWERLEVEL9K_JAVA_VERSION_BACKGROUND=1
  typeset -g POWERLEVEL9K_JAVA_VERSION_FOREGROUND=255
  typeset -g POWERLEVEL9K_JAVA_VERSION_PROJECT_ONLY=true

  #################################[ package: name@version from package.json ]##################
  typeset -g POWERLEVEL9K_PACKAGE_BACKGROUND=5
  typeset -g POWERLEVEL9K_PACKAGE_FOREGROUND=0

  #####################################[ aws: aws profile ]#####################################
  typeset -g POWERLEVEL9K_AWS_SHOW_ON_COMMAND='aws|awscli|terraform|pulumi|terragrunt'
  typeset -g POWERLEVEL9K_AWS_BACKGROUND=208
  typeset -g POWERLEVEL9K_AWS_FOREGROUND=0

  ##############################[ kubecontext: kubernetes context ]#############################
  typeset -g POWERLEVEL9K_KUBECONTEXT_SHOW_ON_COMMAND='kubectl|helm|kubens|kubectx|oc|istioctl|kogito|k9s|helmfile|flux|fluxctl|stern|kubeseal|skaffold|kubent|kubecolor|cmctl|sparkctl'
  typeset -g POWERLEVEL9K_KUBECONTEXT_BACKGROUND=5
  typeset -g POWERLEVEL9K_KUBECONTEXT_FOREGROUND=0
  typeset -g POWERLEVEL9K_KUBECONTEXT_CLASSES=(
    '*'       DEFAULT
  )
  typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_BACKGROUND=5
  typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_FOREGROUND=0

  ################################[ terraform: terraform workspace ]############################
  typeset -g POWERLEVEL9K_TERRAFORM_SHOW_ON_COMMAND='terraform|tf'
  typeset -g POWERLEVEL9K_TERRAFORM_BACKGROUND=5
  typeset -g POWERLEVEL9K_TERRAFORM_FOREGROUND=0

  #######################################[ time: current time ]#################################
  typeset -g POWERLEVEL9K_TIME_BACKGROUND=0
  typeset -g POWERLEVEL9K_TIME_FOREGROUND=7
  typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%I:%M %p}'
  typeset -g POWERLEVEL9K_TIME_UPDATE_ON_COMMAND=false
  typeset -g POWERLEVEL9K_TIME_VISUAL_IDENTIFIER_EXPANSION=

  # Transient prompt settings
  typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=always

  # Instant prompt mode
  typeset -g POWERLEVEL9K_INSTANT_PROMPT=verbose

  # Hot reload disabled for performance
  typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=true

  # If p10k is already loaded, reload configuration
  (( ! $+functions[p10k] )) || p10k reload
}

# Restore options
(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'
